### ISSUE TITLE
[Example] Doubled spans

### ISSUE THREAD

**Issue by jakub-gawlas** [RisingStack/jaeger-node#5]
Hi folks :)

Firstly, great thanks for awesome project!

While tests example from repo (*server1* and *server2*), I observed that spans for `mongodb_cursor` and `http_request` are doubled in Jaeger UI for `server2`. They have all params the same, except `spanID`, which is different. 

This should works this way?

Thanks and cheers 🥂

**Comment by hekike** [comment]
Hi,

thanks for reporting the issue.
For `http_request` it was an issue, fixed in this commit: https://github.com/RisingStack/jaeger-node/commit/79ef8fb172f6d8c9cf78a2c71c3f74a1b2f9cf80

And released in `2.1.2` to npm.

For `mongodb_cursor ` it's okay, check out tags, it's a different communication.
